- name: Deploy with Docker
  hosts: all
  tasks:
  - name: Install Python pip
    apt: 
      name: ['python-pip', 'python3-pip'] 
      state: present
    become: true
    become_user: root

  - name: Install Python Docker package
    pip: 
      name: docker
    become: true
    become_user: root

  - name: Deploy
    docker_container:
      name: lab1
      image: "{{ lab1_image }}"
      state: started
      ports:
        - "8080:80"